basic:
    name: 'https://bbc.com'
    environments:
        production: 'https://bbc.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /news
        - /sport
        - /business
        - /innovation
        - /culture
        - /arts
        - /travel
        - /future-planet
        - /audio
        - /video
        - /live
        - /home
        - /news/topics/c2vdnvdg6xxt
        - /news/war-in-ukraine
        - /news/us-canada
        - /news/uk
        - /news/politics
        - /news/england
        - /news/northern_ireland
        - /news/northern_ireland/northern_ireland_politics
        - /news/scotland
        - /news/scotland/scotland_politics
        - /news/wales
        - /news/wales/wales_politics
        - /news/world/africa
        - /news/world/asia
        - /news/world/asia/china
        - /news/world/asia/india
        - /news/world/australia
        - /news/world/europe
        - /news/world/latin_america
        - /news/world/middle_east
        - /news/in_pictures
        - /news/bbcindepth
        - /news/bbcverify
        - /business/executive-lounge
        - /business/technology-of-business
        - /business/future-of-business
        - /innovation/technology
        - /innovation/science
        - /innovation/artificial-intelligence
        - /innovation/ai-v-the-mind
        - /culture/film-tv
        - /culture/music
        - /culture/art
        - /culture/style
        - /culture/books
        - /culture/entertainment-news
        - /arts/arts-in-motion
        - /travel/destinations
        - /travel/destinations/africa
        - /travel/destinations/antarctica
        - /travel/destinations/asia
        - /travel/destinations/australia-and-pacific
        - /travel/destinations/caribbean
        - /travel/destinations/central-america
        - /travel/destinations/europe
        - /travel/destinations/middle-east
        - /travel/destinations/north-america
        - /travel/destinations/south-america
        - /travel/worlds-table
        - /travel/cultural-experiences
        - /travel/adventures
        - /travel/specialist
        - /future-planet/natural-wonders
        - /future-planet/weather-science
        - /future-planet/solutions
        - /future-planet/sustainable-business
        - /future-planet/green-living
        - /audio/categories
        - /audio/stations
        - /undefined
        - /live/news
        - /live/sport
        - /weather
        - /newsletters
        - /news/live/cn91dxzv4pnt
        - /news/articles/c15ng4g5g0eo
        - /news/live/cwyneele13qt
        - /news/live/cn4we7prv4rt
        - /news/live/ce3v31v01wvt
        - /news/articles/ce929l5z2ldo
        - /news/articles/c934rxzrly1o
        - /news/videos/cgm8rwn1wvno
        - /travel/article/20250430-the-secrets-of-feeding-the-papal-conclave
        - /culture/article/20250507-the-stunning-retro-space-age-homes-that-are-perfect-for-today
        - /travel/article/20250505-where-to-get-new-york-citys-best-chinese-food
        - /worklife/article/20250507-new-pope-catholicism-america-ross-douthat-katty-kay-interview
        - /audio/play/p0l8w823
        - /news/world
        - /news/articles/ce9vzzxpdm7o
        - /news/articles/cg72l1g43vko
        - /news/videos/c86j6z25eejo
        - /news/articles/ce9299nln2ko
        - /news/articles/ckgxg6x2vv4o
        - /reel/video/p0l5vc1h/the-town-where-deer-roam-free-and-mostly-peacefully-
        - /news/videos/cj3x36zpg13o
        - /news/videos/c4g3gwg3dqlo
        - /news/videos/cx262wl9z91o
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
